services:
  nvda-pipeline:
    build: .
    container_name: nvda_predictor
    restart: always
    shm_size: '2gb'  # <--- DO NOT REMOVE THIS
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./src/data_collection/cookies:/app/src/data_collection/cookies