import pandas as pd
import numpy as np

def add_technical_indicators(df):
    """
    Takes a DataFrame with 'close_price' and 'avg_sentiment' and adds
    technical indicators.
    """
    df = df.copy()
    
    # Sort by date ensures lags are correct
    if 'date' in df.columns:
        df['date'] = pd.to_datetime(df['date'])
        df = df.sort_values('date')
    
    # 1. Price Lags (Context: "What was price yesterday?")
    df['price_lag_1'] = df['close_price'].shift(1)
    df['price_lag_3'] = df['close_price'].shift(3)
    df['price_lag_7'] = df['close_price'].shift(7)
    
    # 2. Sentiment Trends (Context: "Is sentiment improving?")
    df['sentiment_ma_3'] = df['avg_sentiment'].rolling(window=3).mean()
    df['sentiment_ma_7'] = df['avg_sentiment'].rolling(window=7).mean()
    
    # 3. Volatility (Context: "How unstable is the market?")
    # Standard deviation of price over last 7 days
    df['volatility_7'] = df['close_price'].rolling(window=7).std()
    
    # 4. Momentum (Simple Rate of Change)
    # (Price Today - Price 5 days ago) / Price 5 days ago
    df['roc_5'] = df['close_price'].pct_change(periods=5)
    
    # Fill NaN values generated by shifting (first 7 days will be empty)
    # backward fill or drop. For training, we drop.
    return df.dropna()

def prepare_inference_features(conn):
    """
    Fetches the last 30 days from DB to calculate indicators for TODAY.
    Returns a single row DataFrame ready for the model.
    """
    # Fetch last 30 days to ensure we have enough data for rolling windows
    query = "SELECT * FROM daily_summary ORDER BY date DESC LIMIT 30"
    df = pd.read_sql(query, conn)
    
    if len(df) < 10:
        return None # Not enough history to calculate lags
    
    # Sort ascending for calculation
    df = df.sort_values('date', ascending=True)
    
    # Add features
    df_features = add_technical_indicators(df)
    
    # Return only the LAST row (which represents "Today" with full context)
    return df_features.iloc[[-1]]