import pandas as pd
import numpy as np

def calculate_rsi(series, period=14):
    """Calculates the Relative Strength Index (RSI)"""
    delta = series.diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=period).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=period).mean()

    rs = gain / loss
    return 100 - (100 / (1 + rs))

def add_technical_indicators(df):
    """
    Transforms raw data into a Rich Quant Dataset.
    """
    df = df.copy()
    
    # 1. Ensure Sort
    if 'date' in df.columns:
        df['date'] = pd.to_datetime(df['date'])
        df = df.sort_values('date')
    
    # ----------------------------------------
    # A. PRICE DERIVATIVES (Market State)
    # ----------------------------------------
    
    # Returns (Stationary data is better for ML than raw price)
    df['pct_change'] = df['close_price'].pct_change()
    
    # Volatility (Standard Deviation of RETURNS, not raw price)
    # This helps the model predict the WIDTH of the interval.
    df['volatility_7'] = df['pct_change'].rolling(window=7).std()
    
    # Momentum (Price relative to 7-day average)
    # > 1.0 means uptrend, < 1.0 means downtrend
    df['momentum_7'] = df['close_price'] / df['close_price'].rolling(window=7).mean()
    
    # RSI (Relative Strength Index)
    # Detects Overbought (>70) / Oversold (<30) conditions
    df['rsi_14'] = calculate_rsi(df['close_price'], period=14)

    # ----------------------------------------
    # B. SENTIMENT DERIVATIVES (The Signal)
    # ----------------------------------------
    
    # Sentiment Trend (Smoothed)
    df['sentiment_ma_3'] = df['avg_sentiment'].rolling(window=3).mean()
    
    # Sentiment Momentum (Are we getting happier or sadder?)
    df['sentiment_change'] = df['avg_sentiment'] - df['avg_sentiment'].shift(1)
    
    # Interaction Term: Sentiment * Volatility
    # Logic: High sentiment matters MORE when the market is volatile.
    df['sent_x_vol'] = df['avg_sentiment'] * df['volatility_7']

    # ----------------------------------------
    # C. RAW LAGS (Context)
    # ----------------------------------------
    df['price_lag_1'] = df['close_price'].shift(1)
    df['price_lag_7'] = df['close_price'].shift(7)

    # Clean NaN values generated by rolling/shifting
    # We drop the first 14 rows because RSI needs 14 days to calculate
    return df.dropna()

def prepare_inference_features(conn):
    # We need 50 days history to calculate RSI(14) and Volatility safely
    query = "SELECT * FROM daily_summary ORDER BY date DESC LIMIT 50"
    df = pd.read_sql(query, conn)
    
    if len(df) < 20: 
        return None
    
    df = df.sort_values('date', ascending=True)
    df_features = add_technical_indicators(df)
    
    if df_features.empty:
        return None
        
    # Return the very last row (representing 'Today's' state)
    return df_features.iloc[[-1]]